name: flutter_neat_and_clean_calendar
description: >-
  Simple and clean flutter calendar with ability to  slide up/down to show
  weekly/monthly calendar.  Fork of
  https://pub.dev/packages/flutter_clean_calendar
version: 0.3.19+41
homepage: https://github.com/rwbr/flutter_neat_and_clean_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^7.0.0
  intl: ^0.19.0
  macos_ui: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

platforms:
  ios:
  android:
  web:
  macos:
